-- MySQL version of IT_CONF_TAXSTRUCTURE (Tax Structure)
CREATE TABLE IF NOT EXISTS IT_CONF_TAXSTRUCTURE (
  TAXSTRCODE DECIMAL(4,0) NOT NULL,
  TAXSTRNAME VARCHAR(50) DEFAULT ' ',
  DESCRIPTION VARCHAR(100) DEFAULT ' ',
  ActiveStatus TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (TAXSTRCODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
