-- MySQL version of IT_CONF_MENUGROUPS (Menu Groups)
CREATE TABLE IF NOT EXISTS IT_CONF_MENUGROUPS (
  APPDAT DECIMAL(8,0) NOT NULL,
  MENGRPCODE DECIMAL(3,0) NOT NULL,
  MENGRPLNGNAME VARCHAR(30) DEFAULT ' ',
  MENGRPSHTNAME VARCHAR(10) DEFAULT ' ',
  SUBMENLNGNAME VARCHAR(30) DEFAULT ' ',
  SUBMENSHTNAME VARCHAR(10) DEFAULT ' ',
  USERID VARCHAR(10) DEFAULT ' ',
  LSTDAT DECIMAL(8,0) DEFAULT 0,
  LSTTIM DECIMAL(4,2) DEFAULT 0,
  ActiveStatus TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (APPDAT, MENGRPCODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
