-- MySQL version of IT_CONF_OUTSES_LINK (Link Outlet Sessions)
CREATE TABLE IF NOT EXISTS IT_CONF_OUTSES_LINK (
  APPDAT DECIMAL(8,0) NOT NULL,
  OUTCODE VARCHAR(3) NOT NULL,
  SESSIONCODE VARCHAR(2) NOT NULL,
  KOTTYPE VARCHAR(2) DEFAULT '0',
  STATIM DECIMAL(4,2) DEFAULT 0,
  ENDTIM DECIMAL(4,2) DEFAULT 0,
  USERID VARCHAR(10) DEFAULT ' ',
  LSTDAT DECIMAL(8,0) DEFAULT 0,
  LSTTIM DECIMAL(4,2) DEFAULT 0,
  ActiveStatus TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (APPDAT, OUTCODE, SESSIONCODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
