-- MySQL version of IT_CONF_UOM (Unit of Measurement)
CREATE TABLE IF NOT EXISTS IT_CONF_UOM (
  UOM_CODE VARCHAR(10) NOT NULL,
  UOM_NAME VARCHAR(50) DEFAULT ' ',
  DESCRIPTION VARCHAR(100) DEFAULT ' ',
  ActiveStatus TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (UOM_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
