-- MySQL version of IT_CONF_PROPERTY (Property Code)
CREATE TABLE IF NOT EXISTS IT_CONF_PROPERTY (
  PROPERTY_CODE VARCHAR(20) NOT NULL,
  PROPERTY_NAME VARCHAR(100) DEFAULT ' ',
  ADDRESS VARCHAR(255) DEFAULT ' ',
  CITY VARCHAR(100) DEFAULT ' ',
  STATE VARCHAR(100) DEFAULT ' ',
  COUNTRY VARCHAR(100) DEFAULT ' ',
  PHONE VARCHAR(20) DEFAULT ' ',
  EMAIL VARCHAR(100) DEFAULT ' ',
  ActiveStatus TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (PROPERTY_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
