-- MySQL version of IT_CONF_ROLES (Department/Costcenter/Designation)
CREATE TABLE IF NOT EXISTS IT_CONF_ROLES (
  ROLE_ID INT AUTO_INCREMENT PRIMARY KEY,
  ROLE_NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(255) DEFAULT ' ',
  ActiveStatus TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
