-- MySQL version of IT_CONF_TBLMAS (Table Master)
CREATE TABLE IF NOT EXISTS IT_CONF_TBLMAS (
  APPDAT DECIMAL(8,0) NOT NULL,
  TABLE_CODE VARCHAR(10) NOT NULL,
  TABLE_NAME VARCHAR(50) DEFAULT ' ',
  SEATS INT DEFAULT 0,
  USERID VARCHAR(10) DEFAULT ' ',
  LSTDAT DECIMAL(8,0) DEFAULT 0,
  LSTTIM DECIMAL(4,2) DEFAULT 0,
  ActiveStatus TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (APPDAT, TABLE_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
