-- MySQL version of IT_CONF_REASONS (Reason Codes)
CREATE TABLE IF NOT EXISTS IT_CONF_REASONS (
  REASON_CODE VARCHAR(10) NOT NULL,
  REASON_DESC VARCHAR(100) DEFAULT ' ',
  ActiveStatus TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (REASON_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
