-- MySQL version of IT_CONF_TBLMAS (Table Master)
CREATE TABLE IF NOT EXISTS IT_CONF_TBLMAS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  outlet_code VARCHAR(10) NOT NULL,
  table_code VARCHAR(10) NOT NULL,
  table_name VARCHAR(50) DEFAULT '',
  seats INT DEFAULT 0,
  table_shape VARCHAR(20) NOT NULL DEFAULT 'rectangle',
  active_status TINYINT(1) NOT NULL DEFAULT 1,
  created_by VARCHAR(20),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified_by VARCHAR(20),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_outlet_table (outlet_code, table_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
