-- MySQL version of IT_CONF_OUTSET (Outlet Setup)
CREATE TABLE IF NOT EXISTS IT_CONF_OUTSET (
  APPDAT DECIMAL(8,0) NOT NULL,
  OUTCODE VARCHAR(3) NOT NULL,
  OUTNAME VARCHAR(30) DEFAULT ' ',
  SHTNAM VARCHAR(10) DEFAULT ' ',
  OUTTYPE DECIMAL(1,0) DEFAULT 1,
  BILInitial VARCHAR(2) DEFAULT '0',
  OUTSET DECIMAL(6,0) DEFAULT 0,
  ActiveStatus TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (APPDAT, OUTCODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
