-- MySQL version of IT_CONF_OUTORDTYP (Outlet Order Types)
CREATE TABLE IF NOT EXISTS IT_CONF_OUTORDTYP (
  APPDAT DECIMAL(8,0) NOT NULL,
  ORDTYPE VARCHAR(20) DEFAULT ' ',
  ORDTYPESHTNAM VARCHAR(10) DEFAULT ' ',
  LSTDAT DECIMAL(8,0) DEFAULT 0,
  LSTTIM DECIMAL(4,2) DEFAULT 0,
  ActiveStatus TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (APPDAT, ORDTYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
