-- MySQL version of IT_CONF_TAXCODE (Tax code)
CREATE TABLE IF NOT EXISTS IT_CONF_TAXCODE (
  TAX_CODE VARCHAR(10) NOT NULL,
  TAX_DESC VARCHAR(100) DEFAULT ' ',
  RATE DECIMAL(8,3) DEFAULT 0,
  ActiveStatus TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (TAX_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
