-- MySQL version of IT_CONF_KITCHENS
CREATE TABLE IF NOT EXISTS IT_CONF_KITCHENS (
  APPDAT DECIMAL(8,0) NOT NULL,
  KITCODE VARCHAR(3) NOT NULL,
  LNGNAM VARCHAR(30) DEFAULT ' ',
  SHTNAM VARCHAR(10) DEFAULT ' ',
  USERID VARCHAR(10) DEFAULT ' ',
  LSTDAT DECIMAL(8,0) DEFAULT 0,
  LSTTIM DECIMAL(4,2) DEFAULT 0,
  ActiveStatus TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (APPDAT, KITCODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
