-- MySQL version of IT_CONF_STEWARD (Steward)
CREATE TABLE IF NOT EXISTS IT_CONF_STEWARD (
  APPDAT DECIMAL(8,0) NOT NULL,
  STEWARD_CODE VARCHAR(10) NOT NULL,
  STEWARD_NAME VARCHAR(50) DEFAULT ' ',
  USERID VARCHAR(10) DEFAULT ' ',
  LSTDAT DECIMAL(8,0) DEFAULT 0,
  LSTTIM DECIMAL(4,2) DEFAULT 0,
  ActiveStatus TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (APPDAT, STEWARD_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
