-- MySQL version of IT_CONF_CCM (Credit Card Master)
CREATE TABLE IF NOT EXISTS IT_CONF_CCM (
  CCTYPE VARCHAR(10) NOT NULL,
  CCCommission DECIMAL(5,2) NOT NULL,
  USERID VARCHAR(10) DEFAULT ' ',
  LSTDAT DECIMAL(8,0) DEFAULT 0,
  LSTTIM DECIMAL(4,2) DEFAULT 0,
  ActiveStatus TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (CCTYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
