-- MySQL version of IT_CONF_MENUMAS (Menu Master)
CREATE TABLE IF NOT EXISTS IT_CONF_MENUMAS (
  APPDAT DECIMAL(8,0) NOT NULL,
  OUTCODE VARCHAR(3) NOT NULL,
  ITMCODE DECIMAL(4,0) NOT NULL,
  ITMNAM VARCHAR(40) DEFAULT ' ',
  SHTNAM VARCHAR(10) DEFAULT ' ',
  MANGRPCODE DECIMAL(3,0) DEFAULT 0,
  SUBMANGRPCODE DECIMAL(3,0) DEFAULT 0,
  ITMRATE DECIMAL(15,3) DEFAULT 0,
  TAXSTRCODE DECIMAL(4,0) NOT NULL,
  DELFLG DECIMAL(1,0) DEFAULT 0,
  USERID VARCHAR(10) DEFAULT ' ',
  LSTDAT DECIMAL(8,0) DEFAULT 0,
  LSTTIM DECIMAL(4,2) DEFAULT 0,
  ActiveStatus TINYINT(1) NOT NULL DEFAULT 1,
  PRPPHT LONGBLOB,
  PRIMARY KEY (APPDAT, OUTCODE, ITMCODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
