-- MySQL version of IT_CONF_OUTORDTYP_LINK (Link Outlet Order Types)
CREATE TABLE IF NOT EXISTS IT_CONF_OUTORDTYP_LINK (
  APPDAT DECIMAL(8,0) NOT NULL,
  KOTTYPE DECIMAL(2,0) NOT NULL,
  USERID VARCHAR(10) DEFAULT ' ',
  LSTDAT DECIMAL(8,0) DEFAULT 0,
  LSTTIM DECIMAL(4,2) DEFAULT 0,
  ActiveStatus TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (APPDAT, KOTTYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
