-- MySQL version of IT_CONF_OUTSES (Outlet Sessions)
CREATE TABLE IF NOT EXISTS IT_CONF_OUTSES (
  APPDAT DECIMAL(8,0) NOT NULL,
  SESSIONCODE VARCHAR(2) NOT NULL,
  SESSIONNAME VARCHAR(20) DEFAULT ' ',
  SESSIONSHTNAM VARCHAR(10) DEFAULT ' ',
  LSTDAT DECIMAL(8,0) DEFAULT 0,
  LSTTIM DECIMAL(4,2) DEFAULT 0,
  ActiveStatus TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (APPDAT, SESSIONCODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
