-- MySQL version of IT_GEN_Users (User Setup)
CREATE TABLE IF NOT EXISTS IT_GEN_Users (
  USER_ID INT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(100) DEFAULT ' ',
  ROLE_ID INT,
  ActiveStatus TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
